name: Deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Prepare to build
        run: gradle clean build

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.1.0
        with:
          email: marcosjava2008@gmail.com
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: currency-converters
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          dockerfile_directory: ./