name: CI to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.HEROKU_REPO_GITHUB }}
          ref: "main"

      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          machine git.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          EOF`
        env:
          EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}

      - name: "Add remote"
        shell: "bash"
        run: |
          heroku git:remote -a currency-converters

      - name: "Push to heroku"
        shell: "bash"
        run: |
          git push heroku main