name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "currency-converters"
          email: ${{secrets.HEROKU_EMAIL}}
          dockerfile: '../../Dockerfile'